#!/usr/bin/env python3
"""Evaluate P8-Lean checkpoint on synthetic scenarios."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any

import numpy as np
import torch

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.environment.action_space import ACTION_NAMES
from src.models.battle_transformer import BattleTransformer, TransformerConfig


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate P8-Lean on synthetic scenarios")
    parser.add_argument("--checkpoint", required=True, help="Path to P8-Lean checkpoint (.pt)")
    parser.add_argument(
        "--scenario-file",
        default="data/synthetic/p8_lean_scenarios.json",
        help="Scenario JSON generated by build_p8_lean_synthetic_scenarios.py",
    )
    parser.add_argument(
        "--output",
        default="reports/p8_lean_synthetic_inference_report.json",
        help="Output report path",
    )
    parser.add_argument("--device", default="cpu")
    return parser.parse_args()


def _load_model(checkpoint_path: Path, device: torch.device) -> BattleTransformer:
    ckpt = torch.load(checkpoint_path, map_location=device)
    raw_cfg: dict[str, Any] = ckpt.get("config", {})

    # Safe defaults + checkpoint overrides.
    cfg = TransformerConfig.p8_lean()
    for k, v in raw_cfg.items():
        if hasattr(cfg, k):
            setattr(cfg, k, v)

    model = BattleTransformer(cfg).to(device)
    model.load_state_dict(ckpt["model_state_dict"], strict=False)
    model.eval()
    return model


def _to_tensor(x: Any, device: torch.device) -> torch.Tensor:
    return torch.tensor(x, dtype=torch.float32, device=device).unsqueeze(0).unsqueeze(0)


def main() -> int:
    args = parse_args()
    device = torch.device(args.device)

    scenario_path = Path(args.scenario_file)
    data = json.loads(scenario_path.read_text(encoding="utf-8"))
    scenarios = data["scenarios"]

    model = _load_model(Path(args.checkpoint), device=device)

    per_scenario: list[dict[str, Any]] = []
    num_correct = 0
    num_legal = 0

    with torch.no_grad():
        for s in scenarios:
            inp = s["inputs"]
            own_team = _to_tensor(inp["own_team"], device)
            opp_team = _to_tensor(inp["opponent_team"], device)
            field = torch.tensor(inp["field"], dtype=torch.float32, device=device).unsqueeze(0).unsqueeze(0)
            context = torch.tensor(inp["context"], dtype=torch.float32, device=device).unsqueeze(0).unsqueeze(0)
            legal_mask = torch.tensor(inp["legal_mask"], dtype=torch.float32, device=device).unsqueeze(0).unsqueeze(0)
            seq_len = torch.tensor([1], dtype=torch.long, device=device)

            output = model(
                own_team,
                opp_team,
                field,
                context,
                legal_mask=legal_mask,
                seq_len=seq_len,
                return_auxiliary=True,
                return_value=False,
            )

            logits = output.policy_logits[0]
            probs = torch.softmax(logits, dim=-1)
            pred = int(torch.argmax(probs).item())

            expected = int(s["expected_action"])
            acceptable = [int(a) for a in s.get("acceptable_actions", [expected])]
            hit = pred == expected
            acceptable_hit = pred in acceptable
            is_legal = bool(inp["legal_mask"][pred] > 0.5)
            num_correct += int(hit)
            num_legal += int(is_legal)

            top3_idx = torch.topk(probs, k=min(3, probs.shape[-1])).indices.tolist()
            per_scenario.append(
                {
                    "scenario_id": s["scenario_id"],
                    "family": s["family"],
                    "pred_action": pred,
                    "pred_action_name": ACTION_NAMES[pred],
                    "pred_prob": float(probs[pred].item()),
                    "expected_action": expected,
                    "expected_action_name": ACTION_NAMES[expected],
                    "expected_prob": float(probs[expected].item()),
                    "top3": [
                        {
                            "action": int(i),
                            "name": ACTION_NAMES[int(i)],
                            "prob": float(probs[int(i)].item()),
                        }
                        for i in top3_idx
                    ],
                    "hit": hit,
                    "acceptable_hit": acceptable_hit,
                    "legal": is_legal,
                }
            )

    summary = {
        "num_scenarios": len(scenarios),
        "top1_accuracy": num_correct / max(len(scenarios), 1),
        "acceptable_set_hit_rate": sum(int(x["acceptable_hit"]) for x in per_scenario)
        / max(len(scenarios), 1),
        "legality_rate": num_legal / max(len(scenarios), 1),
    }

    report = {
        "checkpoint": args.checkpoint,
        "scenario_file": args.scenario_file,
        "summary": summary,
        "per_scenario": per_scenario,
    }

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print(json.dumps(summary, indent=2))
    print(f"Wrote report -> {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
